# Docker Compose for Test Environment
services:
  blog-test:
    build:
      context: .
      args:
        NOTION_DATABASE_ID: ${NOTION_DATABASE_ID}
        NOTION_API_KEY: ${NOTION_API_KEY}
        REVALIDATE_SECRET: ${REVALIDATE_SECRET}
        NOTION_WEBHOOK_SECRET: ${NOTION_WEBHOOK_SECRET}
    container_name: blog-test
    ports:
      - '3005:3000'
    environment:
      - NEXT_PUBLIC_SITE_URL=https://3005.code.ajy720.me
    env_file:
      - .env.test
    restart: unless-stopped
    labels:
      - 'environment=development'
      - 'app=blog'
