# Docker Compose for Test Environment
services:
  blog-test:
    image: ${IMAGE_NAME_WITH_TAG:-ghcr.io/ajy720-workspace/blog:test-latest}
    container_name: blog-test
    ports:
      - '3001:3000'
    environment:
      - NEXT_PUBLIC_SITE_URL=https://blog-test.ajy720.me
    env_file:
      - .env.test
    restart: unless-stopped
    labels:
      - 'environment=test'
      - 'app=blog'
